"""Generate personalized outreach email drafts for top matches."""

from datetime import datetime

TEMPLATES = {
    "guest_speaker": """Subject: Volunteer Speaker Invitation — {event_name} at Cal Poly Pomona

Dear {contact_name},

I'm writing on behalf of the Insights Association West Chapter to connect you with an outstanding industry professional for an upcoming volunteer engagement opportunity.

**Recommended Volunteer:** {volunteer_name}
**Current Role:** {volunteer_title} at {volunteer_company}
**Expertise:** {expertise}

{volunteer_name} is a member of the IA West board serving as {board_role}, and their expertise in {top_tags} aligns strongly with {event_name}. Based on our matching analysis, this is a {score_label} fit ({match_score:.0%} match score).

**Why this match works:**
- {reason_1}
- {reason_2}
- {reason_3}

We'd love to coordinate a {volunteer_role} opportunity. {volunteer_name} is based in {volunteer_region}, and we have IA events in the area that could create a natural touchpoint.

Would you be open to a brief call to discuss how {volunteer_name} could contribute to your program?

Best regards,
IA West Smart Match Team
Insights Association — West Chapter

---
This outreach was generated by IA West Smart Match CRM
Match Score: {match_score:.0%} | Generated: {date}
""",
    "course_guest_lecture": """Subject: Industry Guest Lecture Opportunity — {course_title} ({course_code})

Dear Professor {instructor},

The Insights Association West Chapter has identified a potential guest lecturer who would bring valuable industry perspective to your {course_title} course.

**Recommended Volunteer:** {volunteer_name}
**Current Role:** {volunteer_title} at {volunteer_company}
**Areas of Expertise:** {expertise}

Our matching algorithm identified a {score_label} alignment ({match_score:.0%}) between {volunteer_name}'s expertise and your course content. As a {board_role} on the IA West board, they bring both deep domain knowledge and a passion for mentoring the next generation of marketing professionals.

**Suggested Topics:**
- {topic_1}
- {topic_2}

**Logistics:**
- Your course meets on {days} from {start_time} to {end_time}
- Course mode: {mode}
- {volunteer_name} is based in {volunteer_region}

The IA West regional event calendar includes events near Cal Poly Pomona, creating natural opportunities for in-person engagement.

Would you be interested in scheduling a guest lecture? We're happy to coordinate timing and logistics.

Best regards,
IA West Smart Match Team
Insights Association — West Chapter

---
Generated by IA West Smart Match CRM | {date}
""",
}


def _score_label(score: float) -> str:
    if score >= 0.7:
        return "strong"
    elif score >= 0.5:
        return "good"
    elif score >= 0.3:
        return "moderate"
    return "potential"


def _extract_top_tags(expertise: str, n: int = 3) -> str:
    tags = [t.strip() for t in expertise.split(",") if t.strip()]
    return ", ".join(tags[:n])


def _generate_reasons(match_row) -> list:
    reasons = []
    if match_row.get("topic_relevance", 0) > 0.3:
        reasons.append(f"Strong topic alignment between their expertise ({match_row.get('volunteer_expertise', '')[:60]}...) and the opportunity's focus area")
    else:
        reasons.append(f"Their background in {_extract_top_tags(match_row.get('volunteer_expertise', ''), 2)} brings a complementary perspective")

    if match_row.get("geographic_proximity", 0) >= 0.8:
        reasons.append(f"Located in {match_row.get('volunteer_region', 'the area')}, making in-person participation convenient")
    elif match_row.get("geographic_proximity", 0) >= 0.5:
        reasons.append(f"Based in nearby {match_row.get('volunteer_region', 'region')}, within reasonable travel distance")
    else:
        reasons.append(f"Available for virtual participation from {match_row.get('volunteer_region', 'their region')}")

    # Vary third reason based on available data
    cal_score = match_row.get("calendar_fit", 0.5)
    hist_score = match_row.get("historical_bonus", 0.4)
    if cal_score >= 0.85:
        reasons.append("Their calendar aligns with an upcoming IA regional event, creating a natural travel window for in-person participation")
    elif hist_score >= 0.7:
        reasons.append(f"With extensive industry experience, they exceed the typical seniority threshold for this type of engagement")
    elif match_row.get("student_interest", 0.5) >= 0.8:
        reasons.append("This opportunity has high student demand, maximizing the impact of their volunteer contribution")
    elif match_row.get("role_fit", 0) > 0.5:
        reasons.append("Their skill set directly maps to the volunteer roles needed for this opportunity")
    else:
        reasons.append("Their industry experience provides valuable real-world context for participants")

    return reasons[:3]


def generate_event_outreach(match_row: dict, event_data: dict = None) -> str:
    """Generate outreach email for a CPP event match."""
    event_data = event_data or {}
    reasons = _generate_reasons(match_row)

    return TEMPLATES["guest_speaker"].format(
        event_name=match_row.get("opportunity", "the event"),
        contact_name=event_data.get("contact_name", "Program Coordinator"),
        volunteer_name=match_row.get("volunteer", ""),
        volunteer_title=match_row.get("volunteer_title", "Industry Leader"),
        volunteer_company=match_row.get("volunteer_company", ""),
        expertise=match_row.get("volunteer_expertise", ""),
        board_role=match_row.get("volunteer_role", "Board Member"),
        top_tags=_extract_top_tags(match_row.get("volunteer_expertise", "")),
        score_label=_score_label(match_row.get("match_score", 0)),
        match_score=match_row.get("match_score", 0),
        volunteer_role=event_data.get("volunteer_roles", "guest speaker"),
        volunteer_region=match_row.get("volunteer_region", ""),
        reason_1=reasons[0],
        reason_2=reasons[1],
        reason_3=reasons[2],
        date=datetime.now().strftime("%B %d, %Y"),
    )


def generate_course_outreach(match_row: dict, course_data: dict = None) -> str:
    """Generate outreach email for a course guest lecture match."""
    course_data = course_data or {}
    expertise = match_row.get("volunteer_expertise", "")
    tags = [t.strip() for t in expertise.split(",") if t.strip()]

    topics = []
    if tags:
        topics.append(f"Industry applications of {tags[0]}")
    if len(tags) > 1:
        topics.append(f"Career paths in {tags[1]}")
    if not topics:
        topics = ["Industry trends in market research", "Career development in insights"]

    return TEMPLATES["course_guest_lecture"].format(
        course_title=course_data.get("title", match_row.get("opportunity", "")),
        course_code=course_data.get("course", ""),
        instructor=course_data.get("instructor", ""),
        volunteer_name=match_row.get("volunteer", ""),
        volunteer_title=match_row.get("volunteer_title", "Industry Leader"),
        volunteer_company=match_row.get("volunteer_company", ""),
        expertise=expertise,
        score_label=_score_label(match_row.get("match_score", 0)),
        match_score=match_row.get("match_score", 0),
        board_role=match_row.get("volunteer_role", "Board Member"),
        topic_1=topics[0],
        topic_2=topics[1] if len(topics) > 1 else "Q&A with students",
        days=course_data.get("days", ""),
        start_time=course_data.get("start_time", ""),
        end_time=course_data.get("end_time", ""),
        mode=course_data.get("mode", ""),
        volunteer_region=match_row.get("volunteer_region", ""),
        date=datetime.now().strftime("%B %d, %Y"),
    )


def generate_outreach(match_row: dict, opp_data: dict = None, opp_type: str = "event") -> str:
    """Route to the appropriate template based on opportunity type."""
    if opp_type == "course":
        return generate_course_outreach(match_row, opp_data)
    return generate_event_outreach(match_row, opp_data)


import re
from urllib.parse import quote


def extract_subject_body(full_email: str) -> dict:
    """Split a generated email into subject and body."""
    lines = full_email.strip().split("\n")
    subject = ""
    body_start = 0
    for i, line in enumerate(lines):
        if line.startswith("Subject:"):
            subject = line.replace("Subject:", "").strip()
            body_start = i + 1
            break
    body = "\n".join(lines[body_start:]).strip()
    return {"subject": subject, "body": body, "full_text": full_email}


def generate_mailto_url(to: str, subject: str, body: str) -> str:
    """Generate a mailto: URL with pre-filled fields."""
    # Strip markdown bold markers for plain-text email
    clean_body = body.replace("**", "").replace("*", "")
    return f"mailto:{quote(to)}?subject={quote(subject)}&body={quote(clean_body)}"


def validate_email(email: str) -> bool:
    """Basic email format validation."""
    return bool(re.match(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$', email))


def generate_outreach_ai(match_row: dict, opp_data: dict = None, opp_type: str = "event") -> str | None:
    """Generate an AI-personalized outreach email. Returns None if unavailable."""
    try:
        from src.ai_helpers import ai_personalize_email
        contact_name = ""
        if opp_data:
            contact_name = opp_data.get("contact_name", opp_data.get("instructor", ""))
        return ai_personalize_email(
            volunteer_name=match_row.get("volunteer", ""),
            volunteer_title=match_row.get("volunteer_title", "Industry Leader"),
            volunteer_company=match_row.get("volunteer_company", ""),
            volunteer_expertise=match_row.get("volunteer_expertise", ""),
            volunteer_role=match_row.get("volunteer_role", "Board Member"),
            volunteer_region=match_row.get("volunteer_region", ""),
            opportunity=match_row.get("opportunity", ""),
            opp_type=opp_type,
            contact_name=contact_name,
            match_score=match_row.get("match_score", 0),
            topic_score=match_row.get("topic_relevance", 0),
        )
    except Exception:
        return None
